# ALGORITMO
# 1 SOLICITAR EL VALOR DE LA BASE DEL TRIANGULO EN METROS
# 2 SOLICITAR EL VALOR DE LA ALTURA DEL TRIANGULO EN METROS
# 3 CALCULAR EL AREA USANDO LA FORMULA: AREA=(BASE * ALTURA) / 2
# 4 MOSTRAR EL AREA CALCULADA
# 5 EVALUAR SI EL AREA ES MAYOR QUE 100 EL PROGRAMA DEBE MOSTRAR TRUE, SI ES MENOR O IGUAL MOSTRAR FALSE
# PSEUDOCODIGO
# LEER EL VALOR DE BASE
# LEER EL VALOR DE ALTURA
# CALCULAR EL AREA CON LA FORMULA
# MOSTRAR EL VALOR DE AREA
# SI AREA ES MAYOR QUE 100 MOSTRAR TRUE
# SI AREA ES IGUAL O MENOR QUE 100 MOSTRAR FALSE

Base= float(input("Ingrese el valor de la base del triangulo en metros"))
Altura= float(input("Ingrese el valor de la altura del triangulo en metros"))
Area=(Base*Altura)/2
print("El area del triangulo es de:", Area)
print("¿El area es mayor que 100?", Area>100)
